-- Enriched quotes: a quote is no longer just the literal text.
--
-- - user_reflection: what the user thought when saving it. Not part of the
--   quote, but the user's voice next to it. Optional.
-- - ai_reflection: an interpretation generated by the LLM on demand. Stored
--   only if the user clicks 'save' after seeing it — same "AI scribe, human
--   curates" principle as everywhere else.
-- - linked_quote_ids: ids of related quotes (one citing another, the same
--   author responding to themselves elsewhere, etc.). Soft references — we
--   don't enforce FK because they live in the same table and can be deleted.
-- - ai_reflection_provider / ai_reflection_model / ai_reflection_at: tiny
--   provenance trail for the AI reflection, mirroring extraction_log.

ALTER TABLE quotes
  ADD COLUMN IF NOT EXISTS user_reflection      TEXT,
  ADD COLUMN IF NOT EXISTS ai_reflection        TEXT,
  ADD COLUMN IF NOT EXISTS ai_reflection_provider TEXT,
  ADD COLUMN IF NOT EXISTS ai_reflection_model  TEXT,
  ADD COLUMN IF NOT EXISTS ai_reflection_at     TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS linked_quote_ids     UUID[] NOT NULL DEFAULT ARRAY[]::UUID[];
