export const LEGACY_PARTIAL_EXPORT_SCOPE = {
  kind: 'legacy-partial',
  includes: ['entities', 'relationships', 'quotes'],
  excludes: [
    'momentos',
    'momento_entities',
    'notes',
    'tasks',
    'cronicas_snapshots',
    'atlas_snapshots',
    'chat_threads',
    'chat_messages',
    'spotify_plays',
    'spotify_tokens',
    'x_bookmarks',
    'x_tokens',
    'proactive_suggestions',
    'extraction_log',
    'error_log',
    'ai_task_providers',
    'llm_cache',
    'web_vitals_samples',
  ],
} as const
