export const STRUCTURED_CORE_EXPORT_SCOPE = {
  kind: 'structured-core',
  completeness: 'partial',
  includes: [
    'entities',
    'relationships',
    'quotes',
    'momentos',
    'momento_entities',
    'notes',
    'tasks',
    'blob_references',
  ],
  excludes: [
    'netlify_blobs_binary',
    'oauth_tokens',
    'cronicas_snapshots',
    'atlas_snapshots',
    'chat_threads',
    'chat_messages',
    'spotify_plays',
    'spotify_tokens',
    'x_bookmarks',
    'x_tokens',
    'proactive_suggestions',
    'extraction_log',
    'error_log',
    'ai_task_providers',
    'llm_cache',
    'web_vitals_samples',
  ],
  warnings: [
    'No incluye bytes binarios de Netlify Blobs; respalda media por separado.',
    'No incluye OAuth tokens ni tablas operacionales/derivadas.',
  ],
} as const
